


services:
  ui:
    container_name: ui
    restart: unless-stopped
    build:
      context: .
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "80:80"
    networks:
      - amplec

networks:
  amplec:
    external: true
      
