[tool.poetry]
name = "ui"
version = "0.1.0"
description = ""
authors = ["mo <~>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
